services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: 